name: Create release

# We create releases for all new tags
on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    name: Build release
    environment: Release
    steps:
      # Boilerplate
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install TeX Live
        id: texlive
        uses: zauguin/install-texlive@v3
        with:
          # List the required TeX Live packages in a separate file to allow reuse in
          # different workflows.
          package_file: .github/tl_packages
      - name: Run l3build
        run: l3build ctan -q -H
      # Now create the release (this only runs if the previous steps were successful)
      - name: Create GitHub release
        uses: ncipollo/release-action@880be3d0a71bc0fa98db60201d2cbdc27324f547
        id: release
        with:
          artifacts: "build/distrib/ctan/*.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
